development:
  adapter: postgresql
  encoding: unicode
  database: reminder
  username: habib
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: test_db
  username: test_user
  password: test_password
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: reminder_pod
  username: habib
  password: postgres
  host: localhost
