development:
  adapter: postgresql
  encoding: unicode
  database: reminder_dev
  username: habib
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: reminder_test
  username: habib
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: reminder
  username: habib
  password: postgres
  host: localhost
