development:
  adapter: postgresql
  encoding: unicode
  database: reminder_dev
  username: habib
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_TEST'] %> 
  username: <%= ENV['DATABASE_USERNAME'] %> 
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: reminder
  username: habib
  password: postgres
  host: localhost
