name: checkout out
on: [push]

jobs:
  checkout-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -a
      - uses: actions/checkout@v3
      - name: List Files After
        run: ls -a
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: |
          pwd
          ls -a
      - name: Checkout
        run: |
          pwd
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ 
          secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout master
      - name: List after Files
        run: ls -a
      - name: check git config
        run: |
          pwd
          echo ${{ secrets.GITHUB_TOKEN }}
          cat ./.git/config