name: Push to Master Workflow

on:
  push:
    branches:
      - master

jobs:
  zip-and-email:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: List Files Before
      run: ls -a
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: List Files After
      run: ls -a
    # debug the Username and email settings
    - name: Debug Inputs
      run: |
        echo "Username: ${{ secrets.EMAIL_USERNAME }}"
    # Step 2: Setup Ruby
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.0
    # Step: 3: Install dependency
    - name: Install dependency
      run: |
        gem install bundler -v 2.3.26
        bundle install
    # Step: 4: Run rake Task
    - name: Run Rake Task
      run: |
        bundle exec rake task:print
    # Step 5: Zip a specific folder
    - name: Zip specific folder
      run: |
        mkdir -p zipped
        zip -r ./zipped/locales.zip ./config/locales
    - name: List Files After Zip
      run: ls -a ./zipped
    - name: List files in the zipped folder
      run: |
        unzip -l ./zipped/locales.zip

    # Step 6: Send an email with the zip file attached
    - name: Send email with attachment
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Git Repository Folder
        body: "Attached is the zipped folder from the latest push to master."
        to: salihaansar99@gmail.com
        cc: habib_tum@ymail.com
        from: ${{ secrets.EMAIL_USERNAME }}
        attachments: ./zipped/locales.zip
