name: Repository Events
on: 
  push:
    branches:
      - master
      - "feature/*"
      - test
    paths:
      - "**.js"

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: comments
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3