name: Expression & Contexts
on: [push, pull_request, issues, workflow_dispatch]

run-name: "Ex @${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
  runs-on-issue-and-prs:
    runs-on: ubuntu-latest
    if: contains(fromJson('["push","pull_request"]'), github.event_name)
    steps:
      - name: Run only if issue or pull_request
        run: echo '${{ fromJson('["issues","pull_request"]') }}'
  using-expression-and-contexts:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        id: expression_id
        run: |
          echo ${{ 1 }}
          echo ${{ 'this is a string' }}
          echo ${{ null }}
          echo ${{ true }} 
          echo ${{ 1 > 2 }} 
          echo ${{ 'string' == 'String' }}
      - name: Dump context
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
