name: Manually Triggered
on:
  workflow_dispatch:
    inputs:
      string12:
        description: A string input
        type: string
        required: true
        default: "Default value"
      option_tet:
        description: "An option Input"
        type: choice
        required: true
        default: Option 3
        options:
          - Option 1
          - Option 2
          - Option 3 
      boolean:
        description: 'A boolean option'
        required: false
        type: boolean
      environment:
        description: "Environment"
        type: environment
        required: true
jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_REF
          echo "String: ${{ inputs.string }}"
          echo "Option: ${{ inputs.option }}"
          echo "Boolean: ${{ inputs.boolean }}"
          echo "Enviornment: ${{ inputs.environment }}"

