name: matrix
on: [push]

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.1.4, 2.5.0, 3.2]
    steps:
      - run: ruby -v
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: ruby -v
