name: matrix
on: [push]

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.0.0', '2.2']
    steps:
      - run: ruby -v
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: ruby -v
