name: Status Check Functions
on: [push]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 61
        timeout-minutes: 1
      - name: Step 2
        id: step-2
        continue-on-error: true
        run: exit 1
      - name: Runs on steps 2 failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Step 2 has filed '
      - name: Runs on failure
        if: failure()
        run: echo 'Steps filed '
      - name: Runs on  Success
        if: success()
        run: echo 'it is success '
      - name: Runs on Always
        if: always()
        run: echo ' Always '
      - name: Runs on cancelled
        if: cancelled()
        run: echo ' cancelled '
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo "Job 2"
