name: Status Check Functions
on: [push]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: exit 1
      - name: Step 2
        id: step-2
        run: exit 1
      - name: Runs on failur
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Step 2 has filed '
      - name: Runs on  Success
        if: success()
        run: echo 'Step 2 has filed '
      - name: Runs on Always
        if: always()
        run: echo ' Always '
      - name: Runs on cancelled
        if: cancelled()
        run: echo ' cancelled '
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo "Job 2"
