name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description:
        type: string
        default: "Ali"
        required: false
jobs:
  calling-a-reusable-wf-in-the-same-repo:
    uses: ./.github/workflows/reusable-workflow.yaml
  using-reusable-wf-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-wf-in-the-same-repo
    steps:
      - run: echo ${{ needs.calling-a-reusable-wf-in-the-same-repo.outputs.date }}
