name: workflow run
on:
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
    branches:
      - master

jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered"
